Court_project/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('legal.urls')),
    path('accounts/',include('accounts.urls')),
]

accounts/urls.py
from django.urls import path,include
from . import views



app_name = 'accounts'
urlpatterns = [
    # Include default auth urls
    path('',include('django.contrib.auth.urls')),
    # Registration page.
    path('register/',views.register,name='register'),
]

legal/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views


app_name = 'legal'


urlpatterns = [
    # This is the home page
    path('',views.index,name='index'),
    # This page shows all the case details
    path('cases/',views.cases,name='cases'),
    # Detail page for each case
    path('cases/<int:case_id>/',views.case,name='case'),
    path('new_case/',views.new_case,name='new_case'),
    path('delete_case/<int:case_id>/',views.delete_case,name='delete_case'),
]

accounts/models.py
from django.db import models

# Create your models here.

legal/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class CaseEntry(models.Model):
    """ A case entered by user """
    case_no = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    
    class Meta:
        verbose_name_plural = "Case Entries "
    
    def __str__(self):
        """Return a string representation of the case no """
        return self.case_no
    
    
class CaseDetails(models.Model):
    """Specific details of the case """
    case_no = models.ForeignKey(CaseEntry,on_delete=models.CASCADE)
    description = models.TextField(default='not yet posted')
    judge = models.CharField(max_length=50)
    court_no = models.CharField(max_length=50)
    item = models.CharField(max_length=50)
    date = models.CharField(max_length=50)
    user_id = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = "Case Details"

    def __str__(self):
        return super().__str__()

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm




class CreateUserForm(UserCreationForm):
    email =forms.EmailField()
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

legal/forms.py
from django import forms
from . models import CaseDetails, CaseEntry

class CaseEntryForm(forms.ModelForm):
    class Meta:
        model = CaseEntry
        fields = ['case_no']
        labels = {'case no':''}

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm
# Create your views here.

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = CreateUserForm()
    else:
        # Precess completed form.
        form = CreateUserForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request,new_user)
            return redirect('legal:index')
    # Display a blank or invalid form.
    context = {'form':form}
    return render(request,'registration/register.html',context)

legal/views.py
from http.client import HTTPResponse
from django.http import Http404, HttpResponse 
from django.shortcuts import redirect, render

from legal.forms import CaseEntryForm
from .models import CaseEntry ,CaseDetails
from django.contrib.auth.decorators import login_required
# Create your views here.


def index(request):
    return render(request,'legal/index.html')

@login_required
def cases(request):
    """Show all the Cases"""
    cases = CaseEntry.objects.filter(owner = request.user).order_by('-date_added')
    context = {'cases':cases}
    return render(request,'legal/cases.html',context)                                                               

@login_required
def case(request,case_id):
    """Show details of the case"""
    try: 
        case = CaseDetails.objects.get(id=case_id) 
        # Make sure the case belongs to the current user.
        if case.owner != request.user:
            raise Http404
        context = {'case':case}
        return render(request,'legal/case.html',context)
    except : 
        html = '<h1> Case Details not published yet</h1>'
        return HttpResponse(html)
    
    # if CaseDetails.objects.get(id=case_id):
    #     case = CaseDetails.objects.get(id=case_id)
    #     context = {'case':case}
    #     return render(request,'legal/case.html',context)
    # else:
    #     return render(request,'legal/cases.html')
@login_required
def new_case(request):
    """Add a new case """
    if request.method != 'POST':
        # No data submitted ; create a bland form
        form = CaseEntryForm()
    else:
        # POST data submitted ; Process data.
        form = CaseEntryForm(data=request.POST)
        if form.is_valid():
            new_case = form.save(commit=False)
            new_case.owner = request.user
            new_case.save()
            return redirect('legal:cases')
    # Display a bland or invalid form.
    context = {'form':form}
    return render(request,'legal/new_case.html',context)
    

@login_required
def delete_case(request,case_id):
    case = CaseEntry.objects.get(id=case_id)
    if case.owner != request.user:
        raise Http404
    case.delete()
    return redirect('legal:cases')

legal/templates/legal/base.html
<p>
    <a href="{% url 'legal:index' %}">Legal</a>
    <a href="{% url 'legal:cases' %}">Cases</a>
    {% if user.is_authenticated %}
        Hello, {{ user.username }}.
    {% else %}
        <a href="{% url 'accounts:register' %}">Register</a>
        <a href="{% url 'accounts:login' %}">Log In</a>
    {% endif %}
</p>

{% block content %}

{% endblock content %} 
{% if user.is_authenticated %}
    <hr />
    <form action="{% url 'accounts:logout' %}" method="post">
        {% csrf_token %}
        <button name="submit">Log Out</button>
    </form>
{% endif %}

legal/templates/legal/case.html
{% extends 'legal/base.html' %}
{% block content %}
<p>Case No : {{ case.case_no }}</p>
{% if case %}
<p>{{case.case_no}}</p>
<p>{{case.description}}</p>
<p>{{case.judge}}</p>
<p>{{case.court}}</p>
<p>{{case.date}}</p>
<p>{{case.date_added}}</p>
{% else %}
<li>No case have been added yet.</li>
{% endif %}

{% endblock content %}

legal/templates/legal/cases.html
{% extends 'legal/base.html' %}


{% block content %}
<ul>
    {% for case in cases %}
    <li>
        <a href="{% url 'legal:case' case.id %}">
            {{ case.case_no}}</a>
        <a href="{% url 'legal:delete_case' case.id %}">Delete</a>
    </li>
    {% empty %}
    <li>No case have been added yet.</li>
    {% endfor %}
</ul>
<a href="{% url 'legal:new_case' %}">Add a new case</a>
{% endblock content %}

legal/templates/legal/index.html
{% extends 'legal/base.html' %}

{% block content %}
<p>This is Legal home page</p>
{% endblock content %}

legal/templates/legal/new_case.html
{% extends 'legal/base.html' %}

{% block content %}
<p>Add a new case :</p>
<form action="{% url 'legal:new_case' %}" method="post">
    {% csrf_token %}
    {{ form.as_div }}
    <button name="submit">Add</button>
</form>
{% endblock content %}